cn.tdr.policeequipment.web/Controllers/CabinetController.cs
namespace cn.tdr.policeequipment.web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Newtonsoft.Json.Linq;
    using Models;
    using data.entity;
    using enumerates;
    using module;

    public class CabinetController : AuthController
    {
        // GET: Cabinet
        public ActionResult Index(int w, int h)
        {
            ViewBag.ViewWidth = w;
            ViewBag.ViewHeight = h;
            return View(TableCabinetHeaderModel.Header);
        }

        [HttpGet]
        public JObject GetData(string orgId, string name, int page, int rows)
        {
            var count = 0;
            var module = new CabinetModule(CurrentUser);
            var items = module.Page(orgId, name, page, rows, out count);
            var json = TableCabinetDataModel.Model.GetJson(items, count, TableCabinetHeaderModel.Header);
            return json;
        }

        [HttpGet]
        public JsonResult Tree(string orgId)
        {
            var module = new CabinetModule(CurrentUser);
            var items = module.FeatchAll(orgId).Select(t => new ComboTreeModel
            {
                children = new ComboTreeModel[0],
                id = t.Id,
                text = t.Name
            });
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult FormSubmit(string id, string orgId, string name, double lon, double lat)
        {
            var cabinet = new Cabinet
            {
                IsDel = (short)DeleteStatus.No,
                Lat = lat,
                Lon = lon,
                Name = name,
                OrgId = orgId
            };
            var data = false;
            var module = new CabinetModule(CurrentUser);
            if (string.IsNullOrWhiteSpace(id))
            {
                data = module.Add(cabinet);
            }

            if (!string.IsNullOrWhiteSpace(id))
            {
                cabinet.Id = id;
                data = module.Modify(cabinet, t => t.Id == id);
            }

            return Json(new { code = 0, msg = "Ok", data = data }, "text/html");
        }

        [HttpPost]
        public JsonResult Remove(string id)
        {
            var data = false;
            var module = new CabinetModule(CurrentUser);
            data = module.Remove(t => t.Id == id);
            return Json(new { code = 0, msg = "Ok", data = data });
        }
    }
}

cn.tdr.policeequipment.web/Controllers/OrgController.cs
namespace cn.tdr.policeequipment.web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Newtonsoft.Json.Linq;
    using Models;
    using enumerates;
    using module;

    public class OrgController : AuthController
    {
        // GET: Org
        public ActionResult Index(int w, int h)
        {
            ViewBag.ViewWidth = w;
            ViewBag.ViewHeight = h;
            return View(TableOrgHeaderModel.Header);
        }

        public JObject GetData()
        {
            var m = new OrgModule(CurrentUser);
            var items = m.FetchAll().ToArray();
            if (!CurrentUser.IsSupperAdministrator)
            {
                var root = items.First(t => t.Id == CurrentUser.Organization.Id);
                root.Pid = null;
                var childs = items.Where(t => t.Pid == CurrentUser.Organization.Id);
                var list = new List<data.entity.Organization>();
                list.AddRange(items);
                list.RemoveAll(t => t.Id == CurrentUser.Organization.Id);
                list.Add(root);
                items = list.ToArray();
                list.Clear();
                list = null;
            }
            var json = TableOrgDataModel.Model.GetJson(items, TableOrgHeaderModel.Header);
            return json;
        }

        [HttpGet]
        public JsonResult Tree()
        {
            var m = new OrgModule(CurrentUser);
            var items = m.FetchAll().ToArray();
            var data = 
                items
                .Where(t => string.IsNullOrWhiteSpace(t.Pid) || t.Pid == "0" || t.Id == CurrentUser.Organization.Id)
                .Select(t => GetTree(t, items))
                .ToArray();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        private ComboTreeModel GetTree(data.entity.Organization parent, IEnumerable<data.entity.Organization> orgs)
        {
            var tree = new ComboTreeModel
            {
                id = parent.Id,
                text = parent.Name,
                children = orgs.Where(t => t.Pid == parent.Id).Select(t => GetTree(t, orgs)).ToArray()
            };
            return tree;
        }

        public JsonResult FormSubmit(string id, string name, string code, string parentId)
        {
            var flag = false;
            var mod = new OrgModule(CurrentUser);
            var m = new data.entity.Organization
            {
                Code = code,
                IsDel = (short)DeleteStatus.No,
                Layer = 0,
                Name = name,
                Pid = parentId
            };

            if (string.IsNullOrWhiteSpace(id))
            {
                flag = mod.Add(m);
            }
            else
            {
                m.Id = id;
                flag = mod.Modify(m, t => t.Id == id);
            }
            return Json(new { code = 0, msg = "Ok", data = flag }, "text/html");
        }

        public JsonResult Remove(string id)
        {
            var m = new OrgModule(CurrentUser);
            var flag = m.Remove(t => t.Id == id);
            return Json(new { code = 0, msg = "Ok", data = flag });
        }
    }
}

cn.tdr.policeequipment.web/Views/Cabinet/Index.cshtml
@using cn.tdr.policeequipment.web.Models
@model TableCabinetHeaderModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_PartialDataGrid",
    new DataGridPageModel<TableHeaderModel>
    {
        dataAction = Url.Action("GetData"),
        formModel = new GridEditFormModel
        {
            formPartialPage = "_PartialCabinetForm",
            formAction = Url.Action("FormSubmit"),
            formModel = Model
        },
        headerPartialPage = "_PartialCabinetTableRow",
        headerPartialPageModel = new GridRowModel<TableHeaderModel>
        {
            actionFormart = "fmtOper",
            headerModel = Model
        },
        options = ",pagination:true,pageSize:20",
        toolbarPartialPage = "_PartialCabinetTableBar",
        tableHeight = ViewBag.ViewHeight
    })

@Html.Partial("_PartialMapSelector")

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/pgis/js/EzMapAPI.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/pgis/js/EzServerClient.Extend.js")"></script>
    <script type="text/javascript">

    function getRowData(id, cb) {
        var data = grid().datagrid('getData');
        for (var i = 0; i < data.rows.length; i++) {
            var row = data.rows[i];
            if (row.id == id) {
                cb(row);
                break;
            }
        }
    }

    function onEdit(e, id) {
        getRowData(id, function (row) {
            var defaults = {
                orgId: row.org.id
            };
            $.extend(defaults, row);
            showFormDlg(defaults);
        });
    }

    function onDel(e, id, name) {
        var defaults = {
            name: name,
            url: '@Url.Action("Remove")',
            queryParams: { id: id }
        };
        onDelHd(defaults);
    }

    function fmtOper(val, row) {
        var html = '<span class="x-a-cls" onclick="onEdit(this, \'' + val + '\' )">编辑</span>\
                    <span class="x-a-cls" onclick="onDel(this, \'' + val + '\', \'' + row.name + '\' )">删除</span>';
        return html;
    }

    function fmtSite(val, row) {
        var text = "未绑定";
        if (!!val) {
            text = "已绑定";
        }
        return text;
    }

    function fmtOrg(val, row) {
        return row.org.name;
    }

    function fmtOfficer(val, row) {
        var text = "( 未指定 )";
        if (!!val && !!val.name) {
            text = val.name;
        }
        return text;
    }

    function fmtGps(val, row) {
        var text = "( 未设置 )";
        if (!!row.lon && !!row.lat) {
            text = '( ' + row.lon + ',' + row.lat + ' )';
        }
        return text;
    }

    function mapPointerGps(opts) {
        var defaults = {
            cb: function (data) { }
        };
        $.extend(defaults, opts);

        // 显示 GPS 点选取器
        xmwd.open({
            lon: $('#lon').numberbox('getValue'),
            lat: $('#lat').numberbox('getValue'),
            cb: function (gps) {
                $('#lon').numberbox('setValue', gps.lon);
                $('#lat').numberbox('setValue', gps.lat);
            }
        });
    }

    function loadFormData(data) {
        var defaults = {
            id: null, name: null, orgId: null, lon: 0, lat: 0
        };
        $.extend(defaults, data);
        form().form('load', defaults);
    }

    function showFormDlg(data) {
        loadFormData(data);
        xdlg.open();
    }

    function queryClear() {
        $("#queryOrgId").combotree('setValue', '');
        $('#queryName').textbox('setValue', '');
    }

    setQueryParams({
        orgId: function () { return $('#queryOrgId').val(); },
        name: function () { return $('#queryName').val(); },
        tt: function () { return (new Date()).getTime(); }
    });

    </script>
}

cn.tdr.policeequipment.web/Views/Cabinet/_PartialCabinetForm.cshtml
<div class="x-form-row" style="padding:5px;">
    <input id="name" name="name" class="easyui-textbox"
           data-options="prompt:'警械柜名称 ...',required:true" style="width:100%;height:26px" />
</div>
<div class="x-form-row" style="padding:5px;">
    <input id="orgId" name="orgId" style="width:100%;height:26px" class="easyui-combotree"
           data-options="url:'@Url.Action("Tree", "Org")',method:'get',prompt:'选择组织机构 ...',required:true" />
</div>
<div class="x-form-row" style="padding:5px;">
    <input id="lon" name="lon" class="easyui-numberbox"
           data-options="prompt:'GPS 经度 ...',required:true,precision:8" style="width:30%;height:26px" />
    <span style="height:26px;line-height:26px;font-weight:700;">，</span>
    <input id="lat" name="lat" class="easyui-numberbox"
           data-options="prompt:'GPS 纬度 ...',required:true,precision:8" style="width:30%;height:26px" />
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="mapPointerGps();return false;"
       style="text-align:center;height:26px;line-height:26px;">从地图选择 ... </a>
</div>

cn.tdr.policeequipment.web/Views/Cabinet/_PartialCabinetTableBar.cshtml
<input id="queryOrgId" name="queryOrgId" style="width:25%;height:26px" class="easyui-combotree"
       data-options="url:'@Url.Action("Tree", "Org")',method:'get',prompt:'选择组织机构 ...'" />
<input id="queryName" name="queryName" class="easyui-textbox"
       data-options="prompt:'警械柜名称 ...'" style="width:15%;height:26px" />
<a href="javascript:void(0);" onclick="grid().datagrid('load');" class="easyui-linkbutton" iconCls="icon-search">查询</a>
<a href="javascript:void(0);" onclick="queryClear()" class="easyui-linkbutton">清除</a>
<a href="javascript:void(0);" onclick="showFormDlg()" class="easyui-linkbutton">新增警械柜</a>

cn.tdr.policeequipment.web/Views/Cabinet/_PartialCabinetTableRow.cshtml
@using cn.tdr.policeequipment.web.Models
@model GridRowModel<TableHeaderModel>
@{
    var header = Model.headerModel as TableCabinetHeaderModel;
}
<tr>
    <th data-options="field:'@header.name.field',align:'left',width:3">@header.name.title</th>
    <th data-options="field:'@header.org.field',align:'left',width:3,formatter:fmtOrg">@header.org.title</th>
    <th data-options="field:'@header.site.field',align:'left',width:1,formatter:fmtSite">@header.site.title</th>
    <th data-options="field:'@header.officer.field',align:'left',width:1,formatter:fmtOfficer">@header.officer.title</th>
    <th data-options="field:'@header.gps.field',align:'left',width:2,formatter:fmtGps">@header.gps.title</th>
    <th data-options="field:'@header.id.field',align:'left',formatter:@Model.actionFormart"></th>
</tr>